export const PARTIDOS = [
  { numero: 10, sigla: "REPUBLICANOS", nome: "Republicanos" },
  { numero: 11, sigla: "PP", nome: "Progressistas" },
  { numero: 12, sigla: "PDT", nome: "Partido Democrático Trabalhista" },
  { numero: 13, sigla: "PT", nome: "Partido dos Trabalhadores" },
  { numero: 14, sigla: "MISSÃO", nome: "Partido Missão" },
  { numero: 15, sigla: "MDB", nome: "Movimento Democrático Brasileiro" },
  { numero: 18, sigla: "REDE", nome: "Rede Sustentabilidade" },
  { numero: 20, sigla: "PODE", nome: "Podemos" },
  { numero: 22, sigla: "PL", nome: "Partido Liberal" },
  { numero: 23, sigla: "CIDADANIA", nome: "Cidadania" },
  { numero: 25, sigla: "PRD", nome: "Partido Renovação Democrática" },
  { numero: 29, sigla: "PCO", nome: "Partido da Causa Operária" },
  { numero: 30, sigla: "NOVO", nome: "Partido Novo" },
  { numero: 35, sigla: "DEMOCRATA", nome: "Democrata" },
  { numero: 40, sigla: "PSB", nome: "Partido Socialista Brasileiro" },
  { numero: 43, sigla: "PV", nome: "Partido Verde" },
  { numero: 44, sigla: "UNIÃO", nome: "União Brasil" },
  { numero: 45, sigla: "PSDB", nome: "Partido da Social Democracia Brasileira" },
  { numero: 50, sigla: "PSOL", nome: "Partido Socialismo e Liberdade" },
  { numero: 55, sigla: "PSD", nome: "Partido Social Democrático" },
  { numero: 65, sigla: "PCdoB", nome: "Partido Comunista do Brasil" },
  { numero: 77, sigla: "SOLIDARIEDADE", nome: "Solidariedade" },
  { numero: 80, sigla: "UP", nome: "Unidade Popular" },
] as const;
